import './partials/js/header';
//import './partials/js/all-categories';
//import './partials/js/hero-slider';
import './partials/js/slick.min';
import './partials/js/order-now';
import './partials/js/popular-recipes';
import './partials/js/favorites';
import './partials/js/search-filter';
// import './partials/js/rating';
import './partials/js/pictures_backend';
