import './partials/js/header';
import './partials/js/hero-slider';
import './partials/js/slick.min';
// import './partials/js/pictures_backend';
import './partials/js/all-categories';
import './partials/js/order-now';
import './partials/js/popular-recipes';
import './partials/js/pictures_backend';
import './partials/js/favorites';
import './partials/js/search-filter';
import './partials/js/render-filters-elements';
